// Regenerates tests/golden.mjs from the current rules + content.
// Only run deliberately; a changed golden means a user-visible behavior change.
import { writeFileSync } from 'node:fs';
import { runReplay } from '../js/rules.js';
import { JOURNEY_STAGES, dailyConfig, toRulesConfig, contentHash } from '../js/content.js';

const cfg = toRulesConfig(JOURNEY_STAGES[3]);
const r = runReplay(cfg, [
  { tick: 3, id: 'p1', type: 'turn', dir: 'right' },
  { tick: 10, id: 'p2', type: 'turn', dir: 'down' },
]);
const d = dailyConfig(new Date(Date.UTC(2026, 0, 5)));
const rd = runReplay(toRulesConfig(d), []);

const out = `// GENERATED by tests/record-golden.mjs — review diffs deliberately.
export const GOLDEN = {
  stage4: '${r.finalHash}',
  daily: '${rd.finalHash}',
  content: '${contentHash()}',
};
`;
writeFileSync(new URL('./golden.mjs', import.meta.url), out);
console.log(out);
